//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageRequest", Namespace="http://schemas.datacontract.org/2004/07/Cer.WsFactService.Request")]
    [System.SerializableAttribute()]
    public partial class MessageRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apiKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.WS.Operacion operacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rfcEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.WS.TipoEmisor tipoEmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xmlBase64Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apiKey {
            get {
                return this.apiKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.apiKeyField, value) != true)) {
                    this.apiKeyField = value;
                    this.RaisePropertyChanged("apiKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.WS.Operacion operacion {
            get {
                return this.operacionField;
            }
            set {
                if ((this.operacionField.Equals(value) != true)) {
                    this.operacionField = value;
                    this.RaisePropertyChanged("operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rfcEmisor {
            get {
                return this.rfcEmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.rfcEmisorField, value) != true)) {
                    this.rfcEmisorField = value;
                    this.RaisePropertyChanged("rfcEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.WS.TipoEmisor tipoEmisor {
            get {
                return this.tipoEmisorField;
            }
            set {
                if ((this.tipoEmisorField.Equals(value) != true)) {
                    this.tipoEmisorField = value;
                    this.RaisePropertyChanged("tipoEmisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xmlBase64 {
            get {
                return this.xmlBase64Field;
            }
            set {
                if ((object.ReferenceEquals(this.xmlBase64Field, value) != true)) {
                    this.xmlBase64Field = value;
                    this.RaisePropertyChanged("xmlBase64");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operacion", Namespace="http://schemas.datacontract.org/2004/07/Cer.WsFactService.Request")]
    public enum Operacion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Emision = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelacion = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmisionRetencion = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CancelacionRetencion = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEmisor", Namespace="http://schemas.datacontract.org/2004/07/Cer.WsFactService.Request")]
    public enum TipoEmisor : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Direct = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Provider = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageResponse", Namespace="http://schemas.datacontract.org/2004/07/Cer.WsFactService.Response")]
    [System.SerializableAttribute()]
    public partial class MessageResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HaveErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlBase64Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HaveError {
            get {
                return this.HaveErrorField;
            }
            set {
                if ((this.HaveErrorField.Equals(value) != true)) {
                    this.HaveErrorField = value;
                    this.RaisePropertyChanged("HaveError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlBase64 {
            get {
                return this.XmlBase64Field;
            }
            set {
                if ((object.ReferenceEquals(this.XmlBase64Field, value) != true)) {
                    this.XmlBase64Field = value;
                    this.RaisePropertyChanged("XmlBase64");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.IWsFact")]
    public interface IWsFact {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsFact/ProcessDocument", ReplyAction="http://tempuri.org/IWsFact/ProcessDocumentResponse")]
        PL.WS.MessageResponse ProcessDocument(PL.WS.MessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsFact/ProcessDocument", ReplyAction="http://tempuri.org/IWsFact/ProcessDocumentResponse")]
        System.Threading.Tasks.Task<PL.WS.MessageResponse> ProcessDocumentAsync(PL.WS.MessageRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsFactChannel : PL.WS.IWsFact, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsFactClient : System.ServiceModel.ClientBase<PL.WS.IWsFact>, PL.WS.IWsFact {
        
        public WsFactClient() {
        }
        
        public WsFactClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsFactClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsFactClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsFactClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL.WS.MessageResponse ProcessDocument(PL.WS.MessageRequest request) {
            return base.Channel.ProcessDocument(request);
        }
        
        public System.Threading.Tasks.Task<PL.WS.MessageResponse> ProcessDocumentAsync(PL.WS.MessageRequest request) {
            return base.Channel.ProcessDocumentAsync(request);
        }
    }
}
